---
- name: Deploying the PHP Applicaion to Dev Enviroment
  become: true
  hosts: todo

  tasks:
    - name: Install Nginx
      become: true
      ansible.builtin.apt:
        name: "nginx"
        state: present

    - name: ensure nginx is started and enabled
      ansible.builtin.service:
        name: nginx
        state: started 
        enabled: yes

    - name: Download the artifact
      get_url:
        url: http://52.14.42.172:8082/artifactory/php-todo-app-artifactory/php-todo
        dest: /home/ubuntu/
        url_username: admin
        url_password: G5pSEzZApUqh!M_


    - name: unzip the artifacts
      ansible.builtin.unarchive:
       src: /home/ubuntu/php-todo
       dest: /home/ubuntu/
       remote_src: yes

    - name: deploy the code
      ansible.builtin.copy:
        src: /home/ubuntu/var/lib/jenkins/workspace/php-todo_main/
        dest: /var/www/html/
        force: yes
        remote_src: yes

    - name: remove nginx default page
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted