pipeline {
  
  agent any

  environment {
    ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
  }

  stages{
    stage("Initial cleanup") {
        steps {
          dir("${WORKSPACE}") {
            deleteDir()
          }
        }
      }
  }

  // stages {
  //   stage('Build') {
  //     steps {
  //       script {
  //         sh 'echo "Building Stage"'
  //       }
  //     }
  //   }

  //   stage('Test') {
  //     steps {
  //       script {
  //         sh 'echo "Testing Stage"'
  //       }
  //     }
  //   }

  //   stage('Package') {
  //     steps {
  //       script {
  //         sh 'echo "Packaging Stage"'
  //       }
  //     }
  //   }

  //   stage('Deploy') {
  //     steps {
  //       script {
  //         sh 'echo "Deployment Stage"'
  //       }
  //     }
  //   }

  //   stage('Clean-up') {
  //     steps {
  //       script {
  //         sh 'echo "Clean up Stage"'
  //       }
  //     }
  //   }
  // }
}