pipeline {
  
  agent any

  parameters {
    string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
  }

  environment {
    ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
  }

  stages{
    stage("Initial cleanup") {
        steps {
          dir("${WORKSPACE}") {
            deleteDir()
          }
        }
      }

    stage('Checkout SCM') {
      steps{
      git branch: 'main', url: 'https://github.com/scholarship-task/ansible-capstone-project.git'
      }
    }


    stage('Prepare Ansible For Execution') {
      steps {
        sh 'echo ${WORKSPACE}' 
        sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/ansible.cfg'  
      }
    }

    stage('Run Ansible playbook') {
      steps {
        ansiblePlaybook credentialsId: 'dapetoo-key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/dev', playbook: 'playbooks/site.yaml'
    }
    

  }

}